apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sub-cronjob-1
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - cronjob-1-sample
