---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: cronjob-1-drpc
  labels:
    app: cronjob-1-sample
spec:
  preferredCluster: "PLACEHOLDER-C1-ClusterName"
  drPolicyRef:
    name: PLACEHOLDER-DRPOLICY-NAME
  placementRef:
    kind: PlacementRule
    name: cronjob-1-placement
  pvcSelector:
    matchLabels:
      appname: hello-world
