apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app1_cephfs
  name: busybox-pvc-7
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
  storageClassName: ocs-storagecluster-cephfs
