---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: mdr/daemonset
  labels:
    app: fluentd-1-sample
  name: fluentd-1-sub
spec:
    channel: ramen-fluentd-1/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: fluentd-1-placement
