---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: mdr/logwriter
  labels:
    app: logwriter-1-sample
  name: logwriter-1-sub
spec:
    channel: ramen-logwriter-1/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: logwriter-1-placement
