apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app2_cephfs
  name: busybox-pvc-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 94Gi
  storageClassName: ocs-storagecluster-cephfs
