apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sub-job-1
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - job-1-sample
