---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: mdr/job
  labels:
    app: job-1-sample
  name: job-1-sub
spec:
    channel: ramen-job-1/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: job-1-placement
